#!/bin/bash
#2014-06-20
#Simple script to generate customized ISO image which is created from scratch by Wu Xi

ls -1 baidu* > /dev/null 2>&1

if [ $? = 0 ]
then
read -n 1 -s -p "At least one image exists, are you sure you want to create a new image? [y-Yes|n-No]:" a
case "$a" in
    "Y"|"y")
    echo -e "\n\033[37mStart creating the image...!\033[0m"
    ;;
    "N"|"n")
    echo -e "\n\033[37mExit!\033[0m"
    exit 1
    ;;
    *)
    echo -e "\n\033[37mWrong Answer, exit!\033[0m"
    exit 1
    ;;
esac
fi

cd initramfs-wuxi/
if [ $? = 0 ]
then
    echo -e "\033[37mGenerating initramfs image...\033[0m"
    find . | cpio -o -H newc | gzip > ../isolinux-wuxi/isolinux/wuxi.img
else
    echo 'Failed to change to the target directory, exit!'
    exit 1
fi

sleep 5

cd ../isolinux-wuxi/
if [ $? = 0 ]
then
    echo -e "\033[37mMaking ISO image...\033[0m"
    #shopt -s dotglob
    #cp -avRf /mnt/* /
    #mkisofs -J -R -v -T -l -r -graft-points -V "RHEL4U3 Wu Xi" -o ../wuxi-rhel4u3-$(date +%s).iso -b isolinux/isolinux.bin -c isolinux/boot.cat  -no-emul-boot -boot-load-size 4 -boot-info-table -allow-lowercase .
    mkisofs -o ../baidu-pxe-$(date +%s).iso -b isolinux/isolinux.bin -c isolinux/boot.cat -input-charset utf-8 -no-emul-boot -boot-load-size 4 -boot-info-table ../isolinux-wuxi/
else
    echo 'Failed to change to the target directory, exit!'
    exit 1
fi

sleep 1
echo -e "\033[37mDone!\033[0m"
